// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "0gNi{}Cc#e$[~FG9[NaW":
            case "Mountain":return img`
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
......................1.........................
.....................111........................
.....................111........................
...................111111.......................
...................111111.......................
..................1111111.......................
..................11111111......................
.................111111111......................
.................1111111111.....................
................c1111111111.....................
................cc111111111c....................
...............ccc1111c111cc....................
...............ccc111cc11cccc...................
..............ccccccccc11cccc...................
.............cccccccccccccccc...................
.............ccccccccccccccccc..................
............cccccccccccccccccc..................
............ccccccccccccccccccc.................
...........cccccccccccccccccccc.................
..........cccccccccccccccccccccc................
..........cccccccccccccccccccccc................
.........ccccccccccccccccccccccc................
........ccccccccccccccccccccccccc...............
........ccccccccccccccccccccccccc...............
.......ccccccccccccccccccccccccccc..............
.......ccccccccccccccccccccccccccc..............
......ccccccccccccccccccccccccccccc.............
.....cccccccccccccccccccccccccccccc.............
.....ccccccccccccccccccccccccccccccc............
....cccccccccccccccccccccccccccccccc............
....cccccccccccccccccccccccccccccccc............
...cccccccccccccccccccccccccccccccccc...........
..ccccccccccccccccccccccccccccccccccc...........
..cccccccccccccccccccccccccccccccccccc..........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
