namespace SpriteKind {
    export const Helicopter = SpriteKind.create()
    export const Cloud = SpriteKind.create()
    export const LandingPad = SpriteKind.create()
    export const Mountain = SpriteKind.create()
    export const Ghost = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    copter.vy += -1
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.LandingPad, function (sprite, otherSprite) {
    sprite.setVelocity(0, 0)
    sprite.y += -2
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    copter.vx += -1
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.Cloud, function (sprite, otherSprite) {
    sprite.x += -1 * sprite.vx
    sprite.y += -1 * sprite.vy
    sprite.vx = 0
    sprite.vy = 0
    otherSprite.y += -1
    pause(100)
    otherSprite.y += 1
})
// Control the copter with the + pad
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    copter.vx += 1
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.Ghost, function (sprite, otherSprite) {
    sprite.setVelocity(0, 0)
    sprite.destroy(effects.spray, 500)
    pause(600)
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    copter.vy += 1
})
sprites.onOverlap(SpriteKind.Helicopter, SpriteKind.Mountain, function (sprite, otherSprite) {
    sprite.x += -1 * sprite.vx
    sprite.y += -1 * sprite.vy
    sprite.setVelocity(0, 0)
    sprite.y += -1
    pause(100)
    sprite.y += 1
})
let copter: Sprite = null
game.splash("Cloud Bump", "control pad flying")
scene.setBackgroundColor(9)
copter = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ......................ffff......
    .....ffff.........fffffff.......
    .......fffffffffffff............
    ...............f................
    ...............f................
    ..............ef..eee...........
    ....f.........e..eeff11.........
    ..ffffffff....eee2f.1111........
    .....f......eee222f11111........
    .....f...eee222222f11111e.......
    .....feeee22222222ff11f2e.......
    .....ee22222222222fffff2e.......
    .....e222222222222fffff2e.......
    .....ee22222222222fffff2e.......
    ......ee222222e222222ff2e.......
    .......ee22222ee2222222ee.......
    ........eeee2eee222222ee........
    ...........fe...eeeeee..........
    ...........f........f...........
    ......f....f........f.....f.....
    ......ffffffffffffffffffff......
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Helicopter)
copter.setStayInScreen(true)
// Create and place "clouds"  Sprites
let cloud1 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 1 1 1 1 1 8 . . . . . . 
    . . . 1 1 8 8 8 1 1 1 1 1 1 . . 
    . 8 1 1 8 8 8 8 8 8 8 8 8 1 1 . 
    . 1 8 8 8 1 8 8 8 1 1 8 8 8 1 . 
    1 1 8 8 1 1 1 1 1 8 8 8 1 1 1 . 
    1 1 8 8 8 8 8 1 1 8 1 8 1 1 . . 
    . 1 1 1 1 8 8 8 8 8 8 8 1 8 . . 
    . . . . 1 1 8 8 1 1 8 8 1 . . . 
    . . . . . . 8 8 8 1 1 1 1 . . . 
    . . . . . . 1 1 1 1 . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Cloud)
cloud1.x = 20
cloud1.y = 30
let cloud2 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 1 1 1 1 1 8 . . . . . . 
    . . . 1 1 8 8 8 1 1 1 1 1 1 . . 
    . 8 1 1 8 8 8 8 8 8 8 8 8 1 1 . 
    . 1 8 8 8 1 8 8 8 1 1 8 8 8 1 . 
    1 1 8 8 1 1 1 1 1 8 8 8 1 1 1 . 
    1 1 8 8 8 8 8 1 1 8 1 8 1 1 . . 
    . 1 1 1 1 8 8 8 8 8 8 8 1 8 . . 
    . . . . 1 1 8 8 1 1 8 8 1 . . . 
    . . . . . . 8 8 8 1 1 1 1 . . . 
    . . . . . . 1 1 1 1 . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Cloud)
cloud2.x = 41
cloud2.y = 48
let cloud3 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . 1 1 1 1 1 8 . . . . . . 
    . . . 1 1 8 8 8 1 1 1 1 1 1 . . 
    . 8 1 1 8 8 8 8 8 8 8 8 8 1 1 . 
    . 1 8 8 8 1 8 8 8 1 1 8 8 8 1 . 
    1 1 8 8 1 1 1 1 1 8 8 8 1 1 1 . 
    1 1 8 8 8 8 8 1 1 8 1 8 1 1 . . 
    . 1 1 1 1 8 8 8 8 8 8 8 1 8 . . 
    . . . . 1 1 8 8 1 1 8 8 1 . . . 
    . . . . . . 8 8 8 1 1 1 1 . . . 
    . . . . . . 1 1 1 1 . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Cloud)
cloud3.x = 120
cloud3.y = 40
let landing = sprites.create(img`
    58585858585858585858585858585858
    58585858585858585858585858585858
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ...............ff...............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.LandingPad)
landing.y = 125
let Mountain = sprites.create(img`
    ................................................
    ................................................
    .....................11.........................
    .....................111........................
    .....................111........................
    ....................1111........................
    ....................11111.......................
    ...................111111.......................
    ...................1111111......................
    ..................11111111......................
    ..................11111111......................
    .................1111111111.....................
    .................1111111111.....................
    .................11111111111....................
    ................c11111111111....................
    ................c11111111111....................
    ...............cc1111111111c....................
    ...............cc111111111ccc...................
    ..............cccc111c1111ccc...................
    ..............cccc111c111cccc...................
    .............ccccc111c11cccccc..................
    .............ccccc11cc11cccccc..................
    ............ccccccccccccccccccc.................
    ............ccccccccccccccccccc.................
    ...........cccccccccccccccccccc.................
    ...........ccccccccccccccccccccc................
    ...........ccccccccccccccccccccc................
    ..........cccccccccccccccccccccc................
    ..........ccccccccccccccccccccccc...............
    .........cccccccccccccccccccccccc...............
    .........cccccccccccccccccccccccc...............
    ........cccccccccccccccccccccccccc..............
    ........cccccccccccccccccccccccccc..............
    .......cccccccccccccccccccccccccccc.............
    .......cccccccccccccccccccccccccccc.............
    ......ccccccccccccccccccccccccccccc.............
    ......cccccccccccccccccccccccccccccc............
    .....ccccccccccccccccccccccccccccccc............
    .....ccccccccccccccccccccccccccccccc............
    ....ccccccccccccccccccccccccccccccccc...........
    ....ccccccccccccccccccccccccccccccccc...........
    ....ccccccccccccccccccccccccccccccccc...........
    ...ccccccccccccccccccccccccccccccccccc..........
    ...ccccccccccccccccccccccccccccccccccc..........
    ..ccccccccccccccccccccccccccccccccccccc.........
    ..ccccccccccccccccccccccccccccccccccccc.........
    .cccccccccccccccccccccccccccccccccccccc.........
    .ccccccccccccccccccccccccccccccccccccccc........
    `, SpriteKind.Mountain)
Mountain.setPosition(135, 112)
let Bird = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . b 5 5 b . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . b b b b b 5 5 5 5 5 5 5 b . . 
    . b d 5 b 5 5 5 5 5 5 5 5 b . . 
    . . b 5 5 b 5 d 1 f 5 d 4 f . . 
    . . b d 5 5 b 1 f f 5 4 4 c . . 
    b b d b 5 5 5 d f b 4 4 4 4 b . 
    b d d c d 5 5 b 5 4 4 4 4 4 4 b 
    c d d d c c b 5 5 5 5 5 5 5 b . 
    c b d d d d d 5 5 5 5 5 5 5 b . 
    . c d d d d d d 5 5 5 5 5 d b . 
    . . c b d d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `, SpriteKind.Cloud)
Bird.setPosition(58, 19)
let Ghost = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111ffff.....
    ......fffcdb1bc111cf....
    ....fc111cbfbf1b1b1f....
    ....f1b1b1ffffbfbfbf....
    ....fbfbfffffff.........
    .........fffff..........
    ..........fff...........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Ghost)
Ghost.setPosition(22, 89)
